### ISSUE TITLE
Basic data table (intro version)

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro_docs#18]
## What is the requested web component?

A standard component to list basic data into a table format. This component will not support advanced features like sorting or filtering. 

## Features

1. customize header row
1. customize the table body
1. scale for mobile devices 
1. allow for infinite data

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

<img width="801" alt="Screen Shot 2020-03-05 at 4 43 03 PM" src="https://user-images.githubusercontent.com/181089/76039164-6b1e2d80-5f00-11ea-9fdf-5fa6ce33042d.png">
<img width="685" alt="Screen Shot 2020-03-06 at 10 23 14 AM" src="https://user-images.githubusercontent.com/181089/76111123-8d618b00-5f94-11ea-86c8-c5fab6141a1a.png">

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.

## Additional context

none

**Comment by znewton** [comment]
The examples above are showing what's been built with our CMS. As we expand our usage of our newly rebuilt CMS, it could make sense for Retain Content to work in tandem with Auro to build these Table elements. I don't see that Airplanes page being highly prioritized for conversion to the new CMS, but perhaps there are other spaces.

**Comment by blackfalcon** [comment]
@znewton we released a v1.0 of the auto-table to meet a very basic spec. Please let us know if there are any alterations needed to meet the needs of your team.
