### ISSUE TITLE
Doc site: Documentation Structure Revision

### ISSUE THREAD

**Issue by dlesaca** [AlaskaAirlines/auro_docs#26]
**Is your feature request related to a problem? Please describe.**
I feel that the pages featured in this repo would benefit from a revised document structure. I believe a revision would make it easier to traverse and consume.

**Describe the solution you'd like**

Here's a _draft_ of one way we could organize the documentation:

- Getting started
  - Download
  - Install
- [Components](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/COMPONENTS.md)
  - [Why Custom Elements?](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/WHY_CUSTOMELEMENT.md)
  - - [Custom element polyfill](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/POLYFILL.md)
  - [Custom element technical details](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/TECH_DETAILS.md)
-  [Accessibility](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/A11Y.md)
   - [focus-visible](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/FOCUS_VISIBLE.md)
   - [is-touching](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/IS_TOUCHING.md)
- [Tests](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/TESTS.md)
  - Component Testing
  - Accessibility Testing
- Customization
  - [Alternate custom element CSS build](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/ALT_BUILD.md)
  - [CSS custom properties(CSS variables)](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/CUSTOM_PROPERTIES.md)
- [Babel support](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/BABEL_SUPPORT.md)
- [Browser support](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/BROWSER_SUPPORT.md)
- Troubleshooting
-  [Contributing](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/CONTRIBUTING.md)
   -  [Working Agreement](https://github.com/AlaskaAirlines/OrionStatelessComponents__docs/blob/master/src/WORKING_AGREEMENT.md)

**Comment by blackfalcon** [comment]
Removing WIP status and recycling this to the backlog. This issue is not to be considered part of the Sprint 6 release.

**Comment by blackfalcon** [comment]
Updates to site structure have taken this into consideration.
