### ISSUE TITLE
auro-hyperlinkgroup: blueprint

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro_docs#266]
# Blueprint
We need a blueprint for auro-hyperlinkgroup that matches the features we want to have.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by leeejune** [comment]
After having some discussion with the UI team, we decided that a hyperlink group is not necessary for the horizontal navigation. Tabs will be used for horizontal navigation even though it redirects to another page. @braven112 What should we do with this component?

**Comment by braven112** [comment]
On desktop would users scroll? The current one on content pages only scrolls on mobile.

**Comment by blackfalcon** [comment]
The behavior you are referencing to in the Auro site is actually a benefit of React routing. Just wanted to make sure we were all on the same page. 

There are some things I want to consider here. Given the conversation I had with UX writing and SEO, I did a little research and I am finding out that the assumption that Google dings you for hidden content is not true. 

* https://www.searchenginejournal.com/googles-mueller-on-myth-of-hidden-tab-content/358724/#close
* https://www.searchenginejournal.com/hidden-text-seo/208866/#close

I think our best route for this element is the following 

1. Create the auro-tab element
2. Create the auro-tabpanel element 
3. Create the auro-tabgroup element 

Given these options, users can use these in concert or à la carte to have the flexibility to create the experiences needed. 

I'd argue that when tabs are used as a form of sub-navigation, they should be used as the Auro site does. But when there is content that is accordion-like to be used with a tab interface, then using a component like auro-tabgroup would be a quick and easy way to make this happen. 

When it comes to the tabs on the side, is that expected to travel with the content scrolling? 

@braven112 I don't understand your scroll question?

**Comment by leeejune** [comment]
I added scroll buttons for tabs on desktop. I will be showing this to the UI team for feedback and then add it to the blueprint!

https://www.figma.com/file/2gLpmni1387iInwbN4TPUv/Tab?node-id=1438%3A4040

**Comment by leeejune** [comment]
Do you mind clarifying "trapped height"? The vertical tabs would have the scroll in case the container reduces in size (and have tabs overflow).

**Comment by blackfalcon** [comment]
@leeejune why can't they just scroll down the page with the rest of the content? Unless I am seeing the Figma wrong, I think you want the tabs to scroll async with the content when they are vertical?

**Comment by leeejune** [comment]
@blackfalcon The original intent is for the tabs to move async with the content. I've done some research and it seems like other vertical tabs are async with the content. However, there is a different type of "vertical navigation" that scrolls with the content. I will bring this to the UI team and see what kind of behavior we want to implement.

**Comment by leeejune** [comment]
Covered in the "Tabs" component.
