### ISSUE TITLE
Redesign sdp (backstage)

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/auro_docs#289]
As an EE team
We would love to have our SDP instance themed in Auro
So that we have a branded experience that integrates all the design goodness of Auro.

Repo: https://github.com/Alaska-Airlines-Shared/sdp-backstage
Theming instructions: https://backstage.io/docs/getting-started/app-custom-theme/
Main focus for this initial roll-out is focused on colors.

AC:
The default theme is as close to the default Auro light theme as possible.
Design tokens are imported and used when applicable in the theme.

**Comment by jordanjones243** [comment]
This ticket is moved to blocked as of now. I have not been able to run the SDP repo locally because of issues with Docker and I am waiting for a response/help from the EE team on this.

**Comment by blackfalcon** [comment]
@jordanjones243 this issue is `done`, but it's still open? Is there more work to be done?

**Comment by braven112** [comment]
There is no more work to be done.
