### ISSUE TITLE
Receipt 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro_docs#53]
## What is the requested web component?

> Please provide a short description of the proposed web component

A receipt component would be reusable in any interface where a transaction occurred. This component should be able to be multi-purpose in application and use. 

## Features

> Please list out the features of the proposed web component

1. TBD
1. ...
1. ...
1. ...

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

> If YES to the question above, please list all URLs to prior art and/or attach screenshots for review.

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.

## Additional context

> Please list any other additional information you see necessary to communicate the scope of the proposed web component.

**Comment by erikalanghauser** [comment]
Example from Price Summary on the Payment Page:
![image](https://user-images.githubusercontent.com/34354487/78281563-b6136c80-74cf-11ea-9c4b-9b90da3114c4.png)
https://share.goabstract.com/c116eea0-bb96-41af-9dd3-910bfbfce74b
