### ISSUE TITLE
Auro use dashboard: start UI build

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro_docs#58]
# User story

As a stakeholder, I want to be able to quickly see the status of Auro use, so I can judge the effectiveness and adoption of the Auro design system.

## Outline subtasks or tasks

> Decide which specific steps need to be completed and who is responsible for each of them.

- [x] Create UI infrastructure to run dashboard
- [x] Create dashboard UI that consumes the payload of the Code Scanning API for Auro resources 
- [x] Create automated deployment when code is pushed to MASTER

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once a basic working dashboard is available for consumption within the org via open URL.

**Comment by tsalright** [comment]
Updated the content of this story instead of creating a new one. The Story is still to create a dashboard, I just changed it to consume an API that will be built first. I see these two stories being done in different sprints. This one will take me a little longer to build.

**Comment by tsalright** [comment]
Dashboard is live.
