### ISSUE TITLE
Can't access/load page for icon library

### ISSUE THREAD

**Issue by bmbl3b33** [AlaskaAirlines/auro_docs#84]
I expect to access the icon library. I used this link: [https://auro-prod-site-w2.azurewebsites.net/icons]
and got this message: "Sorry, check with the site admin for error: EISDIR . .
<img width="450" alt="Screen Shot 2020-05-04 at 3 15 00 PM" src="https://user-images.githubusercontent.com/18337595/81020183-1b36e680-8e1d-11ea-8440-657013d7d83f.png">

Desktop:
 - OS: MAC 10.14.5
 - Browser: Chrome 79.0.3945.88

**Comment by blackfalcon** [comment]
@tsalright review issue. Unless 'quick fix' we can kick this down the road. But it needs to be addressed before we GO LIVE.

**Comment by blackfalcon** [comment]
The issue was addressed and pushed to prod
