### ISSUE TITLE
UI Kit Audit

### ISSUE THREAD

**Issue by vidalmenAS** [AlaskaAirlines/auro_docs#86]
# User story

I want to understand what on the UI Kit is Truth and what is Beta.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Audit all content currently in the MASTER branch of the Design System UI Kit
- [ ] Compile list items that have a dev resource and what do not
- [ ] Discuss future stories based on beta components

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the UI Kit has been reviewed and there is a clear understanding of what is in there that has a dev component and what requires a dev plan. 

Once that itemized list is complete, the final deliverable of this story is to discuss new dev plans for the identified components with the PDM. 

## Epic

https://github.com/AlaskaAirlines/auro_docs/issues/98

**Comment by blackfalcon** [comment]
Additional stories that need to come from this work also include: 

1. Breaking the monolith UIKit into individual project files 
1. address a comms plan to communicate the changes to the UIKit and what impact this will have on the designers
1. Create a training/reference document to assist designers with the transition of workflow

**Comment by vidalmenAS** [comment]
[ADSComponentAudit.pdf](https://github.com/AlaskaAirlines/auro_docs/files/4794872/ADSComponentAudit.pdf)
